### ISSUE TITLE
The payload_template option in the MQTT.publish action is deprecated

### ISSUE THREAD

**Issue by zachary-duquette** [zanix/home-assistant-blueprints#2]
The script is using deprecated options when updating to HA 2024.8.

Here's the current warning:
> Deprecated payload_template option used in MQTT publish action call to topic zigbee2mqtt/0xb43a31fffe30590c/set from payload template {"led_effect": {"color": 255, "duration": 255, "effect": "solid", "level": 1}}. Use the payload option instead. In automations templates are supported natively. Update the automation or script to use the payload option instead and restart Home Assistant to fix this issue.

**Comment by zanix** [comment]
Thanks, I'll get this updated when I update to HA 2024.8.
